// <auto-generated />
using CityAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CityAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180417194748_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CityAPI.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CityArea");

                    b.Property<string>("CityName");

                    b.Property<string>("CityPopulation");

                    b.Property<int?>("CountryId");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("CityAPI.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CountryArea");

                    b.Property<string>("CountryName");

                    b.Property<string>("CountryPopulation");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("CityAPI.Models.City", b =>
                {
                    b.HasOne("CityAPI.Models.Country")
                        .WithMany("City")
                        .HasForeignKey("CountryId");
                });
#pragma warning restore 612, 618
        }
    }
}
